name: Test Build Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build_rpi_arm64:
    name: Build Raspberry Pi (ARM64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: third_party
          key: ${{ runner.os }}-rpi-deps-${{ hashFiles('build-deps.sh') }}

      - name: Build in Ubuntu ARM64 Container
        run: |
          # Nettoyage des caractères \r (CRLF) du fichier requirements pour Linux
          CLEANED_REQ=$(tr -d '\r' < tools/requirements-ubuntu.txt)

          docker run --rm --privileged \
            --platform linux/arm64 \
            -v "$PWD":/work \
            -w /work \
            ubuntu:24.04 \
            bash -c "
              apt-get update && \
              apt-get install -y sudo clang cmake make git ${CLEANED_REQ} && \
              ./build-deps.sh 2>&1 | tee build-deps.log && \
              CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
              cmake --build build --parallel 2>&1 | tee build.log && \
              cpack -G TGZ --config build/CPackConfig.cmake
            "

      - name: Package TGZ
        run: |
          set -euo pipefail
          TGZ_PATH="$(find . -maxdepth 1 -type f -name '*.tar.gz' | head -n 1)"
          if [ -z "${TGZ_PATH}" ]; then
            echo "No .tar.gz package found!"
            exit 1
          fi

          SHORT_SHA="${GITHUB_SHA::7}"
          TGZ_NAME="3SX-${SHORT_SHA}-rpi-arm64.tar.gz"
          mv "${TGZ_PATH}" "${TGZ_NAME}"
        shell: bash

      - name: Upload Raspberry Pi release assets
        uses: actions/upload-artifact@v4
        with:
          name: release-assets-rpi
          path: |
            3SX-*-rpi-arm64.tar.gz

      - name: Upload Raspberry Pi build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-rpi
          path: |
            build-deps.log
            build.log